#!/usr/bin/env python3

import rospy
import rosparam
from rosgraph.masterapi import MasterError
from interbotix_copilot.copilot import Copilot
import signal


def main():
    rospy.init_node('copilot')
    try:
        robot_type = rosparam.get_param("copilot/robot_model")
        name = rosparam.get_param("copilot/robot_name")
        group_name = rosparam.get_param("copilot/group_name")
    except MasterError as e:
        print(f"The parameters `robot_model`, `robot_name` and `group` name should be set on the parameter server: {e}")
        raise e
    copilot = Copilot(robot_type=robot_type, name=name, group_name=group_name)
    # copilot.set_logger_level(level="DEBUG")
    rospy.on_shutdown(copilot.shutdown)
    # Ensures that the gui is closed with ctrl + C.
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    copilot.gui()
    while not rospy.is_shutdown():
        copilot.window.show()
        copilot.app.exec()


if __name__ == '__main__':
    main()
